# Generated by Django 3.1.4 on 2020-12-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='trans_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
